### ISSUE TITLE
Support für Multi-Cam

### ISSUE THREAD

**Issue by jazzcrack** [EZTEQ/rbtv-firetv#10]
In der App wurde nicht die reguläre Ranked #28 "Team Limited" Folge gezeigt, sondern "... mit Kommentar von Andy Strauß" ... musste daher leider auf die YouTube App ausweichen, um die reguläre Sendung sehen zu können (ohne Andy Strauß). :-/

**Comment by EZTEQ** [comment]
Entschuldige die späte Antwort. Ich versuche aktuell noch eine Testumgebung für das Multi-Cam Feature nachzustellen.
Gelingt mir das, werde ich mir die Funktion zum Wechseln der verschiedenen Inputs vornehmen.

**Comment by EZTEQ** [comment]
Implemented in 1086dcd5f3068333c9f0b43d0fcc905ca2b53df1
