### ISSUE TITLE
Support for superchad

### ISSUE THREAD

**Issue by Seros** [EZTEQ/rbtv-firetv#13]
As Rocket Beans TV is now broadcasting parallel on youtube and twitch they have introduced the so-called "superchad" on their homepage and under https://rocketbeans.tv/superchad/ . It would be great to see this feature also implemented in your app with added twitch viewer count and hopefully a full emoticon support as the beans don't provide this feature AFAIK. BTW thanks for your great work!

**Comment by EZTEQ** [comment]
Support for the "superchad" is in the works.
I will open a new issue that addresses the addition of the Twitch viewer count to the YouTube viewer count.
