### ISSUE TITLE
YouTube's get_video_info has changed

### ISSUE THREAD

**Issue by simmscmi** [EZTEQ/rbtv-firetv#22]
It seems that YouTube's get_video_info doesn't return data any longer, leading to the RBTV live stream no longer working in the app; adding a _html5=1_ query parameter seems to solve this issue (for now), so adding that to _YouTubeService.kt_ might fix the app (at least temporarily):

[rbtv.patch.txt](https://github.com/markhaehnel/RocketBeansTV.Android/files/6572006/rbtv.patch.txt)

**Comment by markhaehnel** [comment]
Thanks for pointing this out! App release is on it's way.
