### ISSUE TITLE
Schedule doesn't work for me.

### ISSUE THREAD

**Issue by SolidNerd** [EZTEQ/rbtv-firetv#5]
Hey, 
i like your app very well it works for me except the schedule feature. I got only an error toast. 
I have the following specs:

1. Fire TV Version: `Fire OS 5.0.51 (53717552)`
2. Android Version: `Android 5.1`
3. rbtv-firetv Version:  `3.4`

Behaviour:
1. Press the left side on the circle button.
2. Error toast appears.

I hope it helps you to trace the error.

**Comment by EZTEQ** [comment]
First of all, thanks for the bug report.

I can't reproduce the problem. Try to restart the FireTV to fix this.

**Comment by SolidNerd** [comment]
Thanks for your help. A restart solves my problem.
