### ISSUE TITLE
Philips Androide TV

### ISSUE THREAD

**Issue by jadmanx** [EZTEQ/rbtv-firetv#6]
hey die app läuft super auf meinem Philips Androide TV nur zwei dinge.

-wenn ich die app starte dreht sich permanent der rosa kreis, auch wenn das Bild bereits in der perfekten Qualität angezeigt wird. also es verschwindet garnicht selbst nach zwei stunden ist es immer noch da und dreht sich das mir schlecht wird :-).
bei jedem start der app.

-das zweite es wird mir keine app icon am startbildschirm angezeigt. normalerweise sollten dort die letzten apps die ich gestartet habe angezeigt werden. vielleicht weil kein passendes icon für ATV hinterlegt ist ? ich muss es jedesmal mühsam bei "apps verwalten" manuell starten.

wenns wichtig ist mein model ist "PHILIPS 55PUS8700/12"
DANKE tolle arbeit !!!

**Comment by EZTEQ** [comment]
Die App ist hauptsächlich für FireTVs konzipiert. Deshalb kann ich dir leider kein Support für die Probleme mit dem Icon geben.
Anscheinend nutzt Philips nicht die standard App Icons.

Das mit dem Ladekreis konnte ich bisher auch nur auf **nicht** Fire TV Geräten festellen.
Das werde ich mir aber trotzdem einmal anschauen.

**Comment by jadmanx** [comment]
wenn das mit dem kreis behoben wird währe schon super.
wegen dem icon vielleicht hilft dir das 
https://developer.android.com/distribute/essentials/quality/tv.html

**Comment by EZTEQ** [comment]
Habe leider keine Zeit um mich weiter mit dem Thema zu beschäftigen.
